runtime: python39
env: flex
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.7
  max_instances: 4

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

